### PR TITLE
Interface for Lang and Plugin

### PR DESCRIPTION
**Pull request by hvlxh**
\*title\*

### CODE REVIEW

**Comment by andriycraft** [comment]
tests are failing (ignore the auto-format test)

**Comment by hvlxh** [comment]
Because of the your test files

**Comment by hvlxh** [comment]
done of testing @andriycraft

**Comment by NhanAZ** [comment]
I think extension of language files should be .json

**Comment by hvlxh** [comment]
> I think extension of language files should be .json

you can't give or receive types on json.

**Comment by andriycraft** [comment]
JSON is better than JS for lang files

**Comment by hvlxh** [comment]
@andriycraft

**Pull request merged**
