### PR TITLE
Update PlayerInfo.js

### PR DESCRIPTION
**Pull request by AnyBananaGAME**
```
Make PlayerInfo.get not case sensitive
```

### CODE REVIEW

**Comment by andriycraft** [comment]
what if there will be 2 players named `player1` and `plAyer1`

**Comment by AnyBananaGAME** [comment]
idk if that's enough for it to work so might have to test it

**Comment by AnyBananaGAME** [comment]
> what if there will be 2 players named `player1` and `plAyer1`

IT's not possible

**Comment by andriycraft** [comment]
> > what if there will be 2 players named `player1` and `plAyer1`
> 
> IT's not possible

Its possible with offline mode accounts

**Comment by AnyBananaGAME** [comment]
> what if there will be 2 players named `player1` and `plAyer1`

U cant have 2 same names ex: Player and pLayer,
and if it does in offline mode minecraft adds (1) then (2)  and so on at the end

**Comment by andriycraft** [comment]
> > what if there will be 2 players named `player1` and `plAyer1`
> 
> U cant have 2 same names ex: Player and pLayer, and if it does in offline mode minecraft adds (1) then (2) and so on at the end

`bedrock-protocol` can bypass that

**Comment by andriycraft** [comment]
or any other library

**Comment by AnyBananaGAME** [comment]
But it might b different here and shouldnt be hard to add? would balance things out

**Comment by andriycraft** [comment]
I'll merge this to the dev branch (i'll implement username validation later)

**Comment by AnyBananaGAME** [comment]
or prob best thing to do is
Prevent people from joining if a player is already on with that name. Cause it can cause errors in plugins and data collection

**Comment by andriycraft** [comment]
> or prob best thing to do is Prevent people from joining if a player is already on with that name. Cause it can cause errors in plugins and data collection



> I'll merge this to the dev branch (i'll implement **username validation** later)

**Pull request merged**
