### PR TITLE
Add comands & translations

### PR DESCRIPTION
**Pull request by erixweb**
# Changes
- Add /tp & /teleport command
- Add /tell | /w | /whisper | msg
- Add spanish & catalan as a language

### CODE REVIEW

**Comment by andriycraft** [comment]
i'll review this later

**Comment by andriycraft** [comment]
later = 30 minutes

**Comment by andriycraft** [comment]
Only needs to be translated

**Comment by erixweb** [comment]
> Only needs to be translated

I'm kinda busy right now. I'll do the catalan and spanish translations tomorrow

**Comment by andriycraft** [comment]
> > Only needs to be translated
> 
> I'm kinda busy right now. I'll do the catalan and spanish translations tomorrow

I'll do the rest

**Pull request merged**
