### PR TITLE
Made /list look a little bit better, also made some packet docs look better

### PR DESCRIPTION
**Pull request by faaxz**

### CODE REVIEW

**Comment by faaxz** [comment]
i will try to fix subchunks

**Comment by AnyBananaGAME** [comment]
Alr good luck

**Comment by faaxz** [comment]
i found out that the network_published_blablabla packet is not required

**Comment by AnyBananaGAME** [comment]
Some network packwts are required for container packets

**Comment by faaxz** [comment]
> i will try to fix subchunks

in the next update*

**Review by AnyBananaGAME — APPROVED** [review]

**Comment by AnyBananaGAME** [comment]
Why was this still not merged? As this thread is basically just fir correcting the grammar and making code look better

**Comment by andriycraft** [comment]
cuz it is still in draft

**Comment by faaxz** [comment]
not finished

**Comment by AnyBananaGAME** [comment]
Oh alr

**Pull request closed without merging**
