### PR TITLE
Client Send Message test

### PR DESCRIPTION
**Pull request by AnyBananaGAME**

### CODE REVIEW

**Comment by AnyBananaGAME** [comment]
Works on my end idk what github thinks

**Comment by andriycraft** [comment]
it breaks the tests because github is peace of shit

**Comment by AnyBananaGAME** [comment]
Ok thanks

**Comment by AnyBananaGAME** [comment]
It didnt break for me and github worflow said everything is great

**Comment by andriycraft** [comment]
> github worflow said everything is great

Github workflow sometimes break ands say that everything is good even when its not

**Comment by AnyBananaGAME** [comment]
It worked on my device and cant really test on different ones

**Review by andriycraft — APPROVED** [review]

**Pull request merged**
