### PR TITLE
Changes related to Prettier

### PR DESCRIPTION
**Pull request by NhanAZ**

### CODE REVIEW

**Comment by NhanAZ** [comment]
I'm not sure if there are commits with major changes to GreenFrogMCBE that haven't been pushed yet so I don't run `npm run build` to avoid conflicts.
So please pull this pull request and run `npm run build` to see the format changes

**Comment by NhanAZ** [comment]
Added code formatter. Now the code will be automatically reformatted by the workflow via a commit (by andriycraft) every time a commit or a pull request is pushed.

**Comment by NhanAZ** [comment]
Done

**Comment by andriycraft** [comment]
Is it possible to change from what account the "Format document" commits are pushed?

**Comment by andriycraft** [comment]
It worked!

**Review by andriycraft — APPROVED** [review]

**Comment by andriycraft** [comment]
Does this mean i can make commits as any other persion in github?

**Pull request merged**
