### PR TITLE
hvlxh: Changes

### PR DESCRIPTION
**Pull request by hvlxh**
- No prompt, its better bad.
- Fixed Date.
- Better Credits.

### CODE REVIEW

**Comment by andriycraft** [comment]
r u gonna rewrite the cmd system or something?

**Comment by andriycraft** [comment]
should i merge this?

**Comment by andriycraft** [comment]
if no then convert this pr to draft

**Comment by andriycraft** [comment]
Ping me in discord, when you finish

**Comment by NhanAZ** [comment]
I think you should close this PR and create a new one.
Changes should be made individually by multiple PRs rather than multiple changes in a single PR.

**Comment by andriycraft** [comment]
Should i merge this in the 3.0 branch?

**Pull request merged**
