### PR TITLE
Create build.yml

### PR DESCRIPTION
**Pull request by NhanAZ**

### CODE REVIEW

**Comment by NhanAZ** [comment]
It seems that this error is caused by the repo's settings (Action Permissions, Branch Protection,...)
This action works fine at https://github.com/PullRequestEvn/GreenFrogMCBE

**Comment by NhanAZ** [comment]
Settings → Actions → General
Allow GitHub Actions to approve pull requests.

Have you enabled this option andriycraft?

**Comment by NhanAZ** [comment]
Settings -> Action -> General -> Workflow Permissions
And choose Read and write permissions

**Comment by NhanAZ** [comment]
lol prettier faild but format work

**Comment by andriycraft** [comment]
> Settings → Actions → General (https://github.com/andriycraft/GreenFrogMCBE/settings/actions) Allow GitHub Actions to approve pull requests.
> 
> Have you enabled this option andriycraft?

I do not have this option in settings

**Comment by andriycraft** [comment]
This function is only for orgs, and ppl with github pro

**Comment by andriycraft** [comment]
Edit:
This thing works only if the person forked the repo before

**Pull request merged**
