### PR TITLE
Major update: 3.0

### PR DESCRIPTION
**Pull request by andriycraft**

### CODE REVIEW

**Comment by andriycraft** [comment]
TODO:

- More events (20+)
- add support for changing difficulty/gamemode in ingame server settings (@faaxz)
- sound command (for 3.1 update) (@hvlxh)
- better world ticking?
- fall damage?

**Comment by hvlxh** [comment]
what about bubble thing on hotbar

**Review by CulteredSaint — APPROVED** [review]

**Review by CulteredSaint — APPROVED** [review]

**Comment by CulteredSaint** [comment]
> what about bubble thing on hotbar

using set_entity_data it can be fixed

**Comment by andriycraft** [comment]
ik

**Comment by andriycraft** [comment]
i need to rewrite the network code first

**Comment by andriycraft** [comment]
> > what about bubble thing on hotbar
> 
> using set_entity_data it can be fixed

done

**Pull request merged**
