### PR TITLE
typing: use const type for constant values

### PR DESCRIPTION
**Pull request by tutinoko2048**

### CODE REVIEW

**Comment by BufferfishW** [comment]
approved by bufferfish

**Comment by andriycraft** [comment]
Add urself to credits

**Comment by AnyBananaGAME** [comment]
> approved by bufferfish

he sucks tho

**Comment by AnyBananaGAME** [comment]
Buffer sucks not tutinko

**Comment by BufferfishW** [comment]
> Buffer sucks not tutinko

No i dont

**Comment by andriycraft** [comment]
pls use discord for shaming bufferfish @AnyBananaGAME

**Pull request merged**
