### PR TITLE
world support 

### PR DESCRIPTION
**Pull request by andriycraft**

### CODE REVIEW

**Comment by BasToTheMax** [comment]
😳

**Comment by AnyBananaGAME** [comment]
Good job andryi

**Comment by BasToTheMax** [comment]
Good job

**Comment by andriycraft** [comment]
client.write('level_chunk', {
                            x: 0,
                            z: 0,
                            sub_chunk_count: -1,
                            cache_enabled: false,
                            blobs: [],
                            payload: <--- can someone help me with this?
                        })

**Comment by hvlxh** [comment]
oh hell naw bro wtf
image

**Comment by andriycraft** [comment]
💀

**Comment by HerryYT** [comment]
> 

For payload serialization take a look at: https://gist.github.com/Tomcc/a96af509e275b1af483b25c543cfbf37
That's a bunch of work to do, maybe there are some libs you can actually use.

**Comment by andriycraft** [comment]
https://github.com/PrismarineJS/bedrock-protocol/issues/163

**Comment by andriycraft** [comment]
closed. check discord for more info

**Pull request closed without merging**
